<?php

namespace AppBundle\Repository;

/**
 * direccionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class direccionesRepository extends \Doctrine\ORM\EntityRepository
{
}
